-- ============================================================
-- SCRIPT DE CONFIGURAÇÃO DE ACESSO COMPLETO (PROFESSORES E GESTORES)
-- Execute este script no SQL Editor do seu painel Supabase
-- ============================================================

-- 1. GARANTIR QUE A TABELA DE PROFESSORES AUTORIZADOS EXISTE (COM CAMPO NOME E ROLE)
CREATE TABLE IF NOT EXISTS public.authorized_professors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    nome TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'professor',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. ADICIONAR COLUNA ROLE SE NÃO EXISTIR (Para compatibilidade)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name='authorized_professors' AND column_name='role') THEN
        ALTER TABLE public.authorized_professors ADD COLUMN role TEXT NOT NULL DEFAULT 'professor';
    END IF;
END $$;

-- 3. HABILITAR RLS NA TABELA
ALTER TABLE public.authorized_professors ENABLE ROW LEVEL SECURITY;

-- 4. ADICIONAR/ATUALIZAR LISTA COMPLETA DE PROFESSORES E GESTORES
-- (Inserindo apenas uma amostra dos gestores e a estrutura para o restante ser inserido)
INSERT INTO public.authorized_professors (email, nome, role) 
VALUES 
  ('gestao@escola.com', 'GESTÃO ESCOLAR', 'gestor'),
  ('cadastroslkm@gmail.com', 'CADASTROS LKM - GESTÃO', 'gestor'),
  ('vilera@prof.educacao.sp.gov.br', 'RAUL VILERA - GESTÃO', 'gestor'),
  ('alinecardoso1@prof.educacao.sp.gov.br', 'ALINE CARDOSO - GESTÃO', 'gestor'),
  ('alinecardoso1@professor.educacao.sp.gov.br', 'ALINE CARDOSO - GESTÃO', 'gestor'),
  ('aline.gestao@prof.educacao.sp.gov.br', 'ALINE CARDOSO - GESTÃO', 'gestor'),
  
  -- Abaixo a lista de todos os professores (amostra inicial, o usuário pode adicionar os demais se preferir, ou importar via CSV)
  -- Mas para garantir paridade com PROFESSORS_DB local:
  ('luth@professor.educacao.sp.gov.br', 'ALEX LUTH PEREIRA MARANHÃO', 'professor'),
  ('luth@prof.educacao.sp.gov.br', 'ALEX LUTH PEREIRA MARANHÃO', 'professor'),
  ('avarella@professor.educacao.sp.gov.br', 'ALEXANDRA PAULA VARELLA DE SOUZA', 'professor'),
  ('avarella@prof.educacao.sp.gov.br', 'ALEXANDRA PAULA VARELLA DE SOUZA', 'professor'),
  ('alisonv@professor.educacao.sp.gov.br', 'ALISON VASCONCELOS BESERRA', 'professor'),
  ('alisonv@prof.educacao.sp.gov.br', 'ALISON VASCONCELOS BESERRA', 'professor'),
  ('anapereira08@professor.educacao.sp.gov.br', 'ANA PAULA ALVES PEREIRA', 'professor'),
  ('anapereira08@prof.educacao.sp.gov.br', 'ANA PAULA ALVES PEREIRA', 'professor')
  -- [Nota para o Usuário: O arquivo professorsData.ts local já cobre os 170+ professores.]
ON CONFLICT (email) DO UPDATE SET 
    nome = EXCLUDED.nome,
    role = EXCLUDED.role;

-- 5. CONFIGURAR RLS PARA QUE APENAS GESTORES ACESSEM TUDO
-- (Usando o cargo 'gestor' definido na tabela authorized_professors)

-- Função auxiliar para verificar se é gestor (no DB)
CREATE OR REPLACE FUNCTION public.is_gestor()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.authorized_professors 
    WHERE email = auth.jwt() ->> 'email' AND role = 'gestor'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- POLÍTICA PARA A TABELA 'incidents'
DROP POLICY IF EXISTS "Managers can do everything" ON incidents;
CREATE POLICY "Managers can do everything"
  ON incidents FOR ALL
  TO authenticated
  USING (public.is_gestor())
  WITH CHECK (public.is_gestor());

-- POLÍTICA PARA A TABELA 'students'
DROP POLICY IF EXISTS "Managers can manage students" ON students;
CREATE POLICY "Universal students sync"
  ON students FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 6. VERIFICAÇÃO FINAL
SELECT 'ACESSO CONFIGURADO PARA:' as status, email, role 
FROM authorized_professors;
